'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AccountCee
    Public Property ID As Integer
    Public Property Code As String
    Public Property Name As String
    Public Property Active As Boolean
    Public Property SeqNo As Integer
    Public Property Summary As Boolean
    Public Property Total As Boolean
    Public Property Debit As Boolean
    Public Property NodeType As Nullable(Of Integer)
    Public Property Parent_ID As Nullable(Of Integer)
    Public Property Parent_ID1 As Nullable(Of Integer)

    Public Overridable Property AccountCee1 As ICollection(Of AccountCee) = New HashSet(Of AccountCee)
    Public Overridable Property AccountCee2 As AccountCee
    Public Overridable Property AccountChart As ICollection(Of AccountChart) = New HashSet(Of AccountChart)

    Public Overrides Function ToString() As String
        Return Name.ToString()
    End Function

End Class
