'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AccountChart
    Public Property ID As Integer
    Public Property Code As String
    Public Property Name As String
    Public Property Active As Boolean
    Public Property AccountCee_ID As Nullable(Of Integer)

    Public Overridable Property AccountCee As AccountCee
    Public Overridable Property DocumentRow As ICollection(Of DocumentRow) = New HashSet(Of DocumentRow)

End Class
