'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Avis
    Public Property ID As Integer
    Public Property Name As String
    Public Property Active As Boolean
    Public Property dateCreated As Date
    Public Property Address As String
    Public Property City As String
    Public Property PostalCode As String
    Public Property Region As String
    Public Property Email As String
    Public Property Phone As String
    Public Property ContactName As String

End Class
