'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class BilaTest
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Bilancio_1Entities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property AccountCee() As DbSet(Of AccountCee)
    Public Overridable Property AccountChart() As DbSet(Of AccountChart)
    Public Overridable Property Avis() As DbSet(Of Avis)
    Public Overridable Property Document() As DbSet(Of Document)
    Public Overridable Property DocumentRow() As DbSet(Of DocumentRow)
    Public Overridable Property DocumentType() As DbSet(Of DocumentType)
    Public Overridable Property Report() As DbSet(Of Report)

End Class
