'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Document
    Public Property ID As Integer
    Public Property Code As String
    Public Property Name As String
    Public Property Active As Boolean
    Public Property dateReg As Date
    Public Property dateDoc As Date
    Public Property DocNr As String
    Public Property Note As String
    Public Property Amount As Decimal
    Public Property DocumentType_ID As Integer

    Public Overridable Property DocumentType As DocumentType
    Public Overridable Property DocumentRow As ICollection(Of DocumentRow) = New HashSet(Of DocumentRow)

End Class
